title = "Vasconomics"
baseURL = "https://vasconomics.com/"
disqusShortname="vasconomics"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

timeout = 10000

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-164387603-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "This is my first website"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/vlaranjo/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/vascolaranjo/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "uploads/images/stock_market_new.jpg"
  recent_posts_number = 4

  mainSections = ["post"]

  env = "production"

[menu]

[[menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about/"

  [[menu.main]]
    name = "Articles"
    weight = 2
    identifier = "articles"
    url = "/post/"